# Generated by Django 5.2 on 2025-05-02 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du document')),
                ('fichier', models.FileField(upload_to='documents/', verbose_name='Fichier')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('responsable', models.CharField(max_length=100, verbose_name='Responsable')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='archivage.categorie', verbose_name='Catégorie')),
            ],
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ajout', 'Ajout'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('consultation', 'Consultation')], max_length=50, verbose_name='Action')),
                ('utilisateur', models.CharField(max_length=100, verbose_name='Utilisateur')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action")),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='archivage.document', verbose_name='Document')),
            ],
        ),
    ]
