# Generated by Django 4.2.20 on 2025-05-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='visibilite',
            field=models.CharField(choices=[('publique', 'Publique'), ('privee', 'Privée'), ('restreinte', 'Restreinte')], default='publique', max_length=20, verbose_name='Visibilité'),
        ),
    ]
