# Generated by Django 4.2.20 on 2025-05-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivage', '0002_document_visibilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, default=15),
            preserve_default=False,
        ),
    ]
