# Generated by Django 5.1.4 on 2025-05-17 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivage', '0002_document_visibilite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historique',
            options={'ordering': ['-date_action'], 'verbose_name': 'Historique', 'verbose_name_plural': 'Historiques'},
        ),
        migrations.AddField(
            model_name='historique',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archivage.categorie'),
        ),
        migrations.AddField(
            model_name='historique',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Détails'),
        ),
        migrations.AddField(
            model_name='historique',
            name='type_element',
            field=models.CharField(choices=[('document', 'Document'), ('categorie', 'Catégorie'), ('utilisateur', 'Utilisateur')], default='document', max_length=20, verbose_name="Type d'élément"),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom de la catégorie'),
        ),
        migrations.AlterField(
            model_name='historique',
            name='action',
            field=models.CharField(choices=[('ajout_document', 'Ajout de document'), ('modification_document', 'Modification de document'), ('suppression_document', 'Suppression de document'), ('consultation_document', 'Consultation de document'), ('telechargement_document', 'Téléchargement de document'), ('ajout_categorie', 'Ajout de catégorie'), ('modification_categorie', 'Modification de catégorie'), ('suppression_categorie', 'Suppression de catégorie'), ('ajout_utilisateur', "Ajout d'utilisateur"), ('suppression_utilisateur', "Suppression d'utilisateur")], max_length=50, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='historique',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques', to='archivage.document'),
        ),
    ]
