# Generated by Django 5.1.4 on 2025-05-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivage', '0003_alter_historique_options_historique_categorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='visibilite',
            field=models.CharField(choices=[('publique', 'Publique'), ('privee', 'Privée')], default='publique', max_length=20, verbose_name='Visibilité'),
        ),
    ]
