# Generated by Django 5.2 on 2025-05-19 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archivage', '0005_registrationrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationRequest',
        ),
    ]
